#!/usr/bin/env python3
"""Hand-rolled assertion runner for `image_io.py`.

Runs under stock `python3` - no Cinema 4D required. Covers
the PPM reader and the BMP writer end-to-end with synthetic
inputs the test harness can verify byte-for-byte.
"""

from __future__ import annotations

import os
import struct
import sys
import tempfile

_HERE = os.path.dirname(os.path.abspath(__file__))
_PLUGIN_DIR = os.path.dirname(_HERE)
if _PLUGIN_DIR not in sys.path:
    sys.path.insert(0, _PLUGIN_DIR)

import image_io  # noqa: E402

g_total  = 0
g_failed = 0


def check(cond, message):
    global g_total, g_failed
    g_total += 1
    if not cond:
        g_failed += 1
        sys.stderr.write("FAIL: " + message + "\n")


# ---------------------------------------------------------------------------
# PPM reader.
# ---------------------------------------------------------------------------

def test_decode_p6_2x1_maxval_255():
    # Pixel 0 = pure red, pixel 1 = pure green.
    data = b"P6\n2 1\n255\n" + bytes([255, 0, 0,  0, 255, 0])
    w, h, rgb = image_io.decode_ppm_p6(data)
    check(w == 2,                                  "width")
    check(h == 1,                                  "height")
    check(len(rgb) == 6,                           "rgb length")
    check(list(rgb) == [255, 0, 0, 0, 255, 0],     "pixels")


def test_decode_p6_handles_comments():
    # Comments may appear between any two header tokens. The
    # renderer's own writer doesn't emit them, but third-party
    # PPMs do.
    data = (b"P6\n# generated by a 3rd-party tool\n"
            b"2 1\n# comment\n255\n"
            + bytes([0, 0, 255,  255, 255, 0]))
    w, h, rgb = image_io.decode_ppm_p6(data)
    check(w == 2 and h == 1, "dimensions")
    check(list(rgb) == [0, 0, 255, 255, 255, 0],   "pixels")


def test_decode_p6_handles_whitespace_variants():
    # Multiple spaces, tabs, CR/LF mixed - all valid header
    # whitespace per the PPM spec.
    data = b"P6\t1   1\r\n255 " + bytes([10, 20, 30])
    w, h, rgb = image_io.decode_ppm_p6(data)
    check(w == 1 and h == 1, "dimensions")
    check(list(rgb) == [10, 20, 30], "pixel")


def test_decode_p6_scales_maxval_127_to_255():
    # maxval=127 -> a sample of 127 should land at 255.
    data = b"P6\n1 1\n127\n" + bytes([127, 64, 0])
    w, h, rgb = image_io.decode_ppm_p6(data)
    # 127 * 255/127 = 255; 64 * 255/127 ~= 128 (round half up).
    check(rgb[0] == 255, "max sample -> 255")
    check(124 <= rgb[1] <= 132, "mid sample scaled near 128")
    check(rgb[2] == 0, "zero stays zero")


def test_decode_p6_supports_16bit_samples():
    # maxval > 255 -> samples are 16-bit big-endian per spec.
    data = (b"P6\n1 1\n65535\n"
            + bytes([0xFF, 0xFF,  0x00, 0x80,  0x00, 0x00]))
    w, h, rgb = image_io.decode_ppm_p6(data)
    check(rgb[0] == 255, "16-bit max -> 255")
    # 0x0080 / 0xFFFF * 255 ~= 0.5 -> 0 or 1.
    check(rgb[1] <= 1, "16-bit mid -> ~0")
    check(rgb[2] == 0, "16-bit zero -> 0")


def test_decode_p6_rejects_wrong_magic():
    threw = False
    try:
        image_io.decode_ppm_p6(b"P3\n1 1\n255\n0 0 0\n")
    except image_io.PpmDecodeError:
        threw = True
    check(threw, "P3 (ASCII) PPM rejected")


def test_decode_p6_rejects_truncated_body():
    # Header says 2x1 (=6 bytes); supply only 3.
    data = b"P6\n2 1\n255\n" + bytes([1, 2, 3])
    threw = False
    try:
        image_io.decode_ppm_p6(data)
    except image_io.PpmDecodeError as exc:
        threw = "short" in str(exc)
    check(threw, "truncated body raises")


def test_decode_p6_rejects_zero_dimensions():
    threw_w = False
    try:
        image_io.decode_ppm_p6(b"P6\n0 1\n255\n")
    except image_io.PpmDecodeError:
        threw_w = True
    check(threw_w, "width 0 rejected")
    threw_h = False
    try:
        image_io.decode_ppm_p6(b"P6\n1 0\n255\n")
    except image_io.PpmDecodeError:
        threw_h = True
    check(threw_h, "height 0 rejected")


def test_read_ppm_p6_round_trips_through_disk():
    body = bytes([200, 100, 50,  10, 20, 30])
    data = b"P6\n2 1\n255\n" + body
    with tempfile.NamedTemporaryFile(suffix=".ppm", delete=False) as f:
        f.write(data)
        path = f.name
    try:
        w, h, rgb = image_io.read_ppm_p6(path)
        check(w == 2 and h == 1,        "dimensions")
        check(list(rgb) == list(body),  "pixels")
    finally:
        os.unlink(path)


# ---------------------------------------------------------------------------
# BMP writer.
# ---------------------------------------------------------------------------

def _decode_bmp_24(data):
    """Tiny BMP-24 reader for tests. Returns
    (width, height, rgb_top_down)."""
    sig, file_size, _, _, off = struct.unpack_from("<2sIHHI", data, 0)
    check(sig == b"BM", "BMP signature")
    info = struct.unpack_from("<IiiHHIIiiII", data, 14)
    hdr_size, w, h, planes, bpp, comp = info[:6]
    check(hdr_size == 40,          "INFOHEADER size")
    check(planes == 1,             "planes")
    check(bpp == 24,               "bpp")
    check(comp == 0,               "BI_RGB")
    row_bytes  = w * 3
    padded_row = (row_bytes + 3) & ~3
    out = bytearray(w * h * 3)
    for y in range(h):
        # BMP rows are bottom-up.
        src_y = h - 1 - y
        src_off = off + src_y * padded_row
        dst_off = y * row_bytes
        for x in range(w):
            b = data[src_off + 0]
            g = data[src_off + 1]
            r = data[src_off + 2]
            out[dst_off + 0] = r
            out[dst_off + 1] = g
            out[dst_off + 2] = b
            src_off += 3
            dst_off += 3
    return (w, h, bytes(out))


def test_encode_bmp_2x2_round_trips():
    rgb_in = bytes([
        # row 0 (top)
        255,   0,   0,    0, 255,   0,
        # row 1 (bottom)
          0,   0, 255,  255, 255,   0,
    ])
    bmp = image_io.encode_bmp_24(2, 2, rgb_in)
    w, h, rgb_out = _decode_bmp_24(bmp)
    check(w == 2 and h == 2, "dimensions round-trip")
    check(rgb_out == rgb_in, "pixels round-trip top-down")


def test_encode_bmp_pads_rows_to_4_bytes():
    # 3 wide -> 9 bytes per row -> padded to 12.
    rgb_in = bytes([
        10, 20, 30,  40, 50, 60,  70, 80, 90,
    ])
    bmp = image_io.encode_bmp_24(3, 1, rgb_in)
    # Pixel offset is 54; one row padded to 12; total 54+12=66.
    check(len(bmp) == 66, "padded file size")
    # File-size field also reflects the padding.
    file_size = struct.unpack_from("<I", bmp, 2)[0]
    check(file_size == 66, "file_size header field")


def test_encode_bmp_validates_buffer_length():
    threw = False
    try:
        image_io.encode_bmp_24(2, 2, b"\x00" * 5)
    except ValueError:
        threw = True
    check(threw, "wrong buffer length rejected")


def test_encode_bmp_rejects_zero_dimensions():
    threw = False
    try:
        image_io.encode_bmp_24(0, 1, b"")
    except ValueError:
        threw = True
    check(threw, "width=0 rejected")


# ---------------------------------------------------------------------------
# PPM -> BMP end-to-end.
# ---------------------------------------------------------------------------

def test_convert_ppm_to_bmp_default_path_writes_next_to_source():
    body = bytes([
        255, 0, 0,    0, 255, 0,
          0, 0, 255, 255, 255, 0,
    ])
    data = b"P6\n2 2\n255\n" + body
    with tempfile.TemporaryDirectory() as tmp:
        ppm = os.path.join(tmp, "render.ppm")
        with open(ppm, "wb") as f:
            f.write(data)
        bmp_path = image_io.convert_ppm_to_bmp(ppm)
        check(os.path.isfile(bmp_path),     "bmp file exists")
        check(bmp_path.endswith(".bmp"),    "bmp extension")
        check(os.path.dirname(bmp_path)
              == os.path.dirname(os.path.abspath(ppm)),
              "bmp lands next to ppm")
        with open(bmp_path, "rb") as f:
            bmp_bytes = f.read()
        w, h, rgb_out = _decode_bmp_24(bmp_bytes)
        check(w == 2 and h == 2,            "dimensions")
        check(rgb_out == body,              "pixels match")


def test_convert_ppm_to_bmp_explicit_destination():
    body = bytes([10, 20, 30])
    data = b"P6\n1 1\n255\n" + body
    with tempfile.TemporaryDirectory() as tmp:
        ppm = os.path.join(tmp, "src.ppm")
        with open(ppm, "wb") as f:
            f.write(data)
        out = os.path.join(tmp, "nested", "dst.bmp")
        bmp_path = image_io.convert_ppm_to_bmp(ppm, out)
        check(os.path.abspath(out) == bmp_path,
              "explicit destination respected")
        check(os.path.isfile(bmp_path), "destination created")


def test_module_does_not_import_c4d():
    check("c4d" not in sys.modules,
          "image_io pulled c4d into sys.modules")


def main():
    test_decode_p6_2x1_maxval_255()
    test_decode_p6_handles_comments()
    test_decode_p6_handles_whitespace_variants()
    test_decode_p6_scales_maxval_127_to_255()
    test_decode_p6_supports_16bit_samples()
    test_decode_p6_rejects_wrong_magic()
    test_decode_p6_rejects_truncated_body()
    test_decode_p6_rejects_zero_dimensions()
    test_read_ppm_p6_round_trips_through_disk()
    test_encode_bmp_2x2_round_trips()
    test_encode_bmp_pads_rows_to_4_bytes()
    test_encode_bmp_validates_buffer_length()
    test_encode_bmp_rejects_zero_dimensions()
    test_convert_ppm_to_bmp_default_path_writes_next_to_source()
    test_convert_ppm_to_bmp_explicit_destination()
    test_module_does_not_import_c4d()
    print("test_image_io: %d/%d passed" % (g_total - g_failed, g_total))
    return 0 if g_failed == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
