# EmbedPtxAsHeader.cmake — convert a PTX text file into a C
# header that exposes its contents as a `static const char[]`
# array, for runtime upload via OptiX `optixModuleCreate*`.
#
# Inputs (passed as -D variables):
#   PTX_FILE      Absolute path to the PTX file.
#   OUTPUT_HEADER Absolute path to the header to write.
#   SYMBOL_NAME   C identifier for the embedded array.
#
# Output: a single header that defines:
#
#   static const char  ${SYMBOL_NAME}[]   = "...PTX contents...";
#   static const size_t ${SYMBOL_NAME}_size = ...;
#
# Pure-CMake implementation (no `bin2c` dependency); works the
# same on Linux + Windows. Used by the rr_optix CMake target's
# build-time PTX compile + embed pipeline.

if(NOT DEFINED PTX_FILE)
    message(FATAL_ERROR "EmbedPtxAsHeader: PTX_FILE not set")
endif()
if(NOT DEFINED OUTPUT_HEADER)
    message(FATAL_ERROR "EmbedPtxAsHeader: OUTPUT_HEADER not set")
endif()
if(NOT DEFINED SYMBOL_NAME)
    message(FATAL_ERROR "EmbedPtxAsHeader: SYMBOL_NAME not set")
endif()

# Read the PTX file as text. PTX is ASCII so this is safe.
file(READ "${PTX_FILE}" _ptx_contents)

string(LENGTH "${_ptx_contents}" _ptx_size)

# Escape the contents for a C string literal:
# 1. backslash → double-backslash
# 2. double-quote → escaped double-quote
# 3. newline → \n + concatenated string-literal break
string(REPLACE "\\" "\\\\" _ptx_contents "${_ptx_contents}")
string(REPLACE "\"" "\\\"" _ptx_contents "${_ptx_contents}")
string(REPLACE "\n" "\\n\"\n    \"" _ptx_contents "${_ptx_contents}")

set(_header
"// Auto-generated by cmake/EmbedPtxAsHeader.cmake. Do not edit.\n"
"// Source: ${PTX_FILE}\n"
"#pragma once\n"
"\n"
"#include <cstddef>\n"
"\n"
"static const char ${SYMBOL_NAME}[] =\n"
"    \"${_ptx_contents}\";\n"
"\n"
"static const std::size_t ${SYMBOL_NAME}_size = ${_ptx_size};\n")

file(WRITE "${OUTPUT_HEADER}" ${_header})
